name: Dependabot Alert to Jira Ticket
on:
  workflow_dispatch:
    inputs:
      pr_label:
        description: Label of PR
        type: string
        required: true
  pull_request:
    types:
      - labeled

jobs:
  create-ticket:
    # Create Ticket
    name: Create Ticket
    uses: velocitycareerlabs/monorepo/.github/workflows/dependabot-create-ticket.yml@dev
    with:
      pr_label: github.event.label.name
    secrets: inherit